version: '3.5'

services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/xyz-vsp-be-video
    ports:
      - '3000:3000'
    links:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HTTP_SESSION_SECRET=wipers
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TWILIO_ACCOUNT_SID=AC6ad9665056687cd4dbc0af8ce6678fb1
      - TWILIO_AUTH_TOKEN=ff08f968072f7968138066a82f391203
      - TWILIO_API_KEY=SK5edd641af653a7b5907a8161be7470a9
      - TWILIO_API_SECRET=rInfu5I6KX7UIgWK77PM5bMDI5sHJbnM
      - MONGO_URI=mongodb://8be6cefd-0ee0-4-231-b9ee:YLo7SWYwiDXb5RTeHJ8cI6UdEL9ZKa8r1SroQpTs1OiZSMsjWwA6LkZsVYkRNVLmslVLWDxsST7dqkK8QCfa0Q%3D%3D@8be6cefd-0ee0-4-231-b9ee.documents.azure.com:10255/?ssl=true
