const {
  PORT,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  REDIS_PREFIX,
  CALLS_DB_URI,
  CALLS_DB_NAME,
  HTTP_SESSION_SECRET,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_API_KEY,
  TWILIO_API_SECRET,
  TWILIO_VOICE_CALL_TWIML_APP_SID,
  AZURE_TENANT_NAME,
  AZURE_TENANT_ID,
  AZURE_CLIENT_ID,
  AZURE_POLICY_NAME,
  LOGSTASH_ENABLED,
  LOGSTASH_PORT,
  LOGSTASH_HOST,
  LOGSTASH_NODE_NAME,
  LOGSTASH_CONNECTION_RETRIES,
  LOGSTASH_CONNECTION_RETRIES_TIMEOUT,
  NEXMO_API_KEY,
  NEXMO_API_SECRET,
  NEXMO_APPLICATION_ID,
  NEXMO_PATH_TO_PRIVATE_KEY,
} = process.env;

module.exports = {
  server: {
    port: PORT || 3000,
  },
  console: {
    enabled: true,
  },
  redis: {
    port: Number(REDIS_PORT) || 6380,
    host: REDIS_HOST || '127.0.0.1',
    password: REDIS_PASSWORD,
    authRequired: Boolean(REDIS_PASSWORD),
    prefix: REDIS_PREFIX || 'VSP_CALLS_Prefix_',
  },
  logstash: {
    enabled: Boolean(LOGSTASH_ENABLED),
    port: LOGSTASH_PORT,
    host: LOGSTASH_HOST,
    nodeName: LOGSTASH_NODE_NAME,
    connectionRetries: Number(LOGSTASH_CONNECTION_RETRIES) || Infinity,
    connectionRetriesTimeout: Number(LOGSTASH_CONNECTION_RETRIES_TIMEOUT) || 60,
  },
  mongoose: {
    connectionString:
    CALLS_DB_URI ||
      'mongodb://customer:secret123@ds111765.mlab.com:11765/calls',
    dbName: CALLS_DB_NAME || 'calls',
    debug: true,
  },
  session: {
    enabled: true,
    secret: HTTP_SESSION_SECRET || 'wipers',
  },
  twilio: {
    accountSid: TWILIO_ACCOUNT_SID,
    authToken: TWILIO_AUTH_TOKEN,
    apiKey: TWILIO_API_KEY,
    apiSecret: TWILIO_API_SECRET,
    voiceCallTwimlAppSid: TWILIO_VOICE_CALL_TWIML_APP_SID,
  },
  azure: {
    identityMetadata: `https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0/.well-known/openid-configuration/`,
    issuer: `https://${AZURE_TENANT_NAME}.b2clogin.com/${AZURE_TENANT_ID}/v2.0/`,
    clientID: AZURE_CLIENT_ID,
    policyName: AZURE_POLICY_NAME,
    isB2C: true,
    validateIssuer: true,
    loggingLevel: 'error',
    passReqToCallback: true,
    loggingNoPII: false,
  },
  nexmo: {
    apiKey: NEXMO_API_KEY || 'aa27ba82',
    apiSecret: NEXMO_API_SECRET || 'eKLLBvDBA875kh20',
    applicationId: NEXMO_APPLICATION_ID,
    privateKey: NEXMO_PATH_TO_PRIVATE_KEY,
  },
};
